FROM eclipse-temurin:21
LABEL maintainer="ahmednagy12474@gmail.com"
WORKDIR /app

COPY target/register-server-0.0.1-SNAPSHOT.jar /app/register-server.jar


ENTRYPOINT ["java", "-jar", "register-server.jar"]
