version: '3.8'
services:
  register-server:
    container_name: register-server
    build:
      context: ./register-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - springapimysql-net

  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - eureka.client.service-url.defaultZone=http://register-server:8761/eureka
    depends_on:
      - register-server
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8089/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - springapimysql-net

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - eureka.client.service-url.defaultZone=http://register-server:8761/eureka
    depends_on:
      - register-server
    networks:
      - springapimysql-net


  bike-server:
    container_name: bike-server
    build:
      context: ./BikeService
      dockerfile: Dockerfile
    networks:
      - springapimysql-net
    environment:
      - eureka.client.service-url.defaultZone=http://register-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8089
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
      - spring.zipkin.base-url=http://zipkin:9411/
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/bikedb?allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

    depends_on:
      - register-server
      - config-server
      - rabbitmq
      - zipkin
      - mysqldb
    ports:
      - "8000:8000"
  rabbitmq:
    container_name: rabbitmq
    networks:
      - springapimysql-net
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bikedb
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  springapimysql-net:
    name: springapimysql-net


volumes:
    mysql_data:
      name: mysql_data