FROM eclipse-temurin:21
LABEL maintainer="ahmednagy12474@gmail.com"
WORKDIR /app

COPY target/RentalRecordService-0.0.1-SNAPSHOT.jar /app/RentalRecordService.jar


ENTRYPOINT ["java", "-jar", "RentalRecordService.jar"]
